apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-toolchain-deploy
spec:
  selector:
    matchLabels:
      app: tekton-toolchain-hello-world
  replicas: 3
  template:
    metadata:
      labels:
        app: toolchain-hello-world
    spec:
      containers:
        - name: toolchain-hello-world
          image: us.icr.io/sfripp-imgs/sfripp-tekton-toolchain-hello-world
          ports:
            - containerPort: 8080
      imagePullSecrets:
          - name: all-icr-io
---
apiVersion: v1
kind: Service
metadata:
  name: tekton-toolchain-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: tekton-toolchain-hello-world
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton-toolchain-ingress
spec:
  ingressClassName: public-iks-k8s-nginx
  rules:
    - host: tekton.build-labs-latam-iks-2bef1f4b4097001da9502000c44fc2b2-0000.us-south.containers.appdomain.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tekton-toolchain-service
                port:
                  number: 8080
